project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: tidyselect

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Functions
      desc: ''
      contents:
        - name: eval_select
          dynamic: true
